# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install prometheus prometheus-community/kube-prometheus-stack -f  prometheus/prometheus.yaml


grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.yamunadevops.online